name: Workflow Dispatch Freeform Input Example

on:
 workflow_dispatch:
   inputs:
     environment:
       description: 'The environment to deploy to'
       required: true
       default: 'production'

jobs:
  deploy:
    run-on: ubuntu-latest
    steps:
      - run: echo "Deploy to ${{ GitHub.event.inputs.environment }} environment
